name: 'graphql-data'
description: 'GraphQL data scrape'
inputs:
  graphql-url:  
    description: 'HTTP(s) endpoint for GraphQL'
    required: false
    default: 'https://api.github.com/graphql'
  bearer-token:  
    description: 'Auth token used as bearer token. In GitHub, use Personal Access Token.'
    required: false
    default: ''
  bearer-token-override:  
    description: 'You know your GraphQL endpoint does not require a bearer token so you override that requirement.'
    required: false
    default: 'false'
  query:  
    description: 'GraphQL query'
    required: false
    default: ''
  query-variables:  
    description: 'GraphQL variables'
    required: false
    default: ''
  github-graphql-default-org:  
    description: 'GitHub org name default value'
    required: false
    default: 'Azure Samples'
outputs:
  data: # id of output
    description: 'GraphQL data returned as JSON object'
runs:
  using: 'node16'
  main: 'dist/index.js'